version: 2
jobs:
  cargo_fetch:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
            - cargo-cache-{{ checksum "Cargo.toml" }}
            - cargo-cache-
      - run: git submodule sync
      - run: git submodule update --init
      - run: cargo fetch
      - save_cache:
          key: cargo-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo/registry
            - /usr/local/cargo/git
  rustfmt:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - run:
          name: Install rustfmt
          command: rustup component add rustfmt
      - run:
          name: Print version information
          command: cargo fmt -- --version
      - run:
          name: Check rustfmt
          command: cargo fmt -- --check
  build_debug:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
            - cargo-cache-{{ checksum "Cargo.toml" }}
            - cargo-cache-
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build
          command: cargo build --frozen
      - persist_to_workspace:
          root: target
          paths:
            - debug/*
  test_debug:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
            - cargo-cache-{{ checksum "Cargo.toml" }}
            - cargo-cache-
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Test
          command: cargo test --frozen --verbose

  build_release:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
            - cargo-cache-{{ checksum "Cargo.toml" }}
            - cargo-cache-
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build in release profile
          command: cargo build --release --frozen
      - persist_to_workspace:
          root: target
          paths:
            - release/*

  test_release:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
            - cargo-cache-{{ checksum "Cargo.toml" }}
            - cargo-cache-
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Test
          command: cargo test --release --frozen --verbose

  test_nightly:
    docker:
      - image: rustlang/rust:nightly
    working_directory: /mnt/crate
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          keys:
            - cargo-cache-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
            - cargo-cache-{{ checksum "Cargo.toml" }}
            - cargo-cache-
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: Build and test with nightly Rust
          command: cargo test --frozen --verbose

  test_jcli_debug:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: ./testing/scripts/jcli.sh

  test_xchain_debug:
    docker:
      - image: rust:latest
    working_directory: /mnt/crate
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run: ./testing/scripts/xchain.sh

workflows:
  version: 2
  test_all:
    jobs:
      - cargo_fetch
      - rustfmt
      - build_debug:
          requires:
            - rustfmt
            - cargo_fetch
      - build_release:
          requires:
            - rustfmt
            - cargo_fetch
      - test_debug:
          requires:
            - build_debug
      - test_release:
          requires:
            - build_release
      - test_nightly:
          requires:
            - rustfmt
            - cargo_fetch
      - test_jcli_debug:
          requires:
            - build_debug
      - test_xchain_debug:
          requires:
            - build_debug
